import Footer from '@/components/Footer'
import Navbar from '@/components/Navbar'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'ACS',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className='flex flex-col justify-between min-h-screen '>
        <div>
          <Navbar />
          <div className={inter.className + " mx-24"}>
            {children}
          </div>
        </div>
        <Footer />
      </body>
    </html>
  )
}
